# Generated by Django 3.2.8 on 2021-11-07 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfoundation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='subscription',
            field=models.CharField(choices=[('OR', 'Orange'), ('AP', 'Apple'), ('BA', 'Banana')], default='OR', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
